[package]
name = "io-nns-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
candid.workspace = true
ic-stable-structures.workspace = true
io-accounts = { path = "../io_accounts" }
io-receipt-types.workspace = true
serde.workspace = true
sha2 = "0.10.9"
