[package]
name = "io-nns-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
candid.workspace = true
ic-stable-structures.workspace = true
ic-cdk.workspace = true
io-accounts = { version = "0.1.0", path = "../io_accounts" }
io-core-model = { version = "0.1.0", path = "../io_core_model" }
io-receipt-types.workspace = true
io-reward-policy.workspace = true
serde.workspace = true
sha2 = "0.10.9"
