[provenance]
official_ic_repository = "dfinity/ic"
official_ic_source_commit = "4320fdf2e613844eabae1927b1a23b98da3a7bc6"
sns_testing_source_path = "rs/sns/testing"
complete = false
blocker_report = "blocker-report.md"
