[package]
name = "mock-io-ledger"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
io-ledger-types.workspace = true
io-ledger-boundary.workspace = true
io-accounts = { version = "0.1.0", path = "../../../crates/io_accounts" }
serde.workspace = true
