[package]
name = "mock-nns-governance"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
io-accounts = { version = "=0.1.0", path = "../../../crates/io_accounts" }
io-nns-types = { version = "=0.1.0", path = "../../../crates/io_nns_types" }
serde.workspace = true
